on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean package

    - name: Run the app and print memory usage
      run: |
        java -jar app/airports-search-jar-with-dependencies.jar -Xmx7m > stdout.log 2> stderr.log &
        APP_PID=$!
        sleep 10s
        ps -p $APP_PID -o rss=
